= Notes on Reactive Programming

include::intro.adoc[leveloffset=+1]

== Reactive Programming in Java

include::flux.adoc[leveloffset=+1]

== The Role of Back Pressure

* `subscribeOn()` allows a `Flux` to relay a slow publisher

* `publishOn()` allows a `Flux` to have slow subscribers

TODO: tidy this up...

since callback is called for each subscriber you can use operators that share a context


 ```
Mono.defer( () -> {
  AtomicInteger d = new AtomicNumber();     
  return Mono.just(1)
             .map(d::incrementAndGet)
             .doOnError(d::decrementAndGet);
})
```

`d` here is scoped for a given `Subscriber` that can be useful


== Don't Be the Bottleneck

Do you need to know all this stuff? Possibly not. You can be the bottleneck, if you are confident that you are no worse than your downstream dependencies. You might as well stick with plain old imperative programming and synchronous request-response. Use a few background threads to grease your way a bit. The result is easier to understand and easier to operationalize.

== Links

http://blog.paralleluniverse.co/2014/02/20/reactive/[Parallel universe blog on Reactive]

http://www.javaworld.com/article/2071370/core-java/of-fibers-and-continuations.html[Of Fibers and Continuations | JavaWorld]

Readable (but unfortunately database-biased) article:
http://news.dice.com/2014/01/13/how-is-reactive-different-from-procedural-programming/[How is Reactive Programming Different?]

Propaganda: 
http://www.reactivemanifesto.org/[The Reactive Manifesto]

http://www.reactive-streams.org/[Reactive Streams]

Blog from RxJava lead http://akarnokd.blogspot.co.uk/[David Karnok] including the one on http://akarnokd.blogspot.co.uk/2016/03/operator-fusion-part-1.html[Generations of Reactive]

https://en.wikipedia.org/wiki/Continuation(which you can think of as state)[Continuation - Wikipedia]

A multilingual framework (including Java):
https://github.com/kentuckyfriedtakahe/sodium[Sodium - GitHub]

http://docs.oracle.com/javase/tutorial/essential/concurrency/forkjoin.html[Fork-join docs at Oracle]

Sebastien Deleuze's https://spring.io/blog/2016/04/19/understanding-reactive-types[Reactive Types] Blog

https://lmax-exchange.github.io/disruptor/[LMAX Disruptor]